project:
  type: website
  output-dir: docs

website:
  title: "Data Analytics Workshop PIE"
  sidebar:
    background: primary
    logo: "images/pie.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Pakillo/quarto-course-website-template
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      - href: https://github.com/zahedasghar/R4D
        text: Forum

format:
  html:
    theme: [default, custom.css, styles.scss]
    # css: styles.css
    toc: true

execute:
  freeze: auto

