---
title: "[Data Analytics workshop with R]{.flow}"
subtitle: "[PERI, UNICEF]{style=color:blue;}"
author: "Zahid Asghar, School of Economics, QAU, Islamabad"
format: 
  html:
    theme: [default, custom.css, styles.scss]
    toc: true
    toc-location: right
    reference-location: document

---


## What will you learn

Basic feature of this workshop will be to start exploring and modeling data using R along-with hands-on experience. All workshops recording, codes, slides and related things will be provided to all the participants once they will join for the workshop.

## By the end of Data Analysis with R, you'll understand:

-   How to use base R and tidyverse to carry out analysis on your own data
-   The core features of a data analysis workflow
-   Generating summary statistics, visualizing and doing econometrics

## And you'll be able to use:

-   Basic functions in the tidyverse to process raw data for typical data analysis questions
-   Logical expressions and indexing to ask specific questions of data
-   Functions to conduct common statistical tests
-   Application of concepts on a real data sets in economics and social sciences

## Why this is for you

-   You have your own data sets and you want to analyze it
-   You think R is important but intimidated by R and dont know where to start with
-   You want to do good in data analytics
-   You want to get data insight for your intelligent decision making
-   You want to be at par in evidence-based research, policy analysis,academia, gig economy worker with the rest of the world

## Uploaded data and required R packages

Understanding datasets requires many hours/days or in some cases weeks.There are many commercially available softwares but open source community based softwares have now dominated and R is one of these. R makes data understanding process as easy as possible through the dplyr package. It is one of the easiest solution for code-based data analysis. We will learn in this training how to do it. 

## Preparation
In order to avoid a sluggish and organization-heavy start of the course, installation of all software components used in this course is to be completed in advance. Preparatory readings are not mandatory but may decrease the learning curve.

## Setting up R, R-Studio and Git(Hub)
If you’ve never used R, R-Studio or Git(Hub) before, start by installing each software component. I suggest you to do so in the following order:

Install [R](https://www.r-project.org/).

Install [R-Studio](https://www.rstudio.com/products/rstudio/download/#download).

Create a [GitHub](https://github.com/) account. Take some care with the user-name if you want to keep this account throughout your career. You can’t change it afterwards.

Install [Git](https://git-scm.com/downloads).

1. Open a shell. On windows, Git comes with its own shell. Open it by searching for “Git Bash”. On Mac, just search for your “Terminal” application. Enter the following commands:

`git config --global user.name 'Your name'' 

'git config --global user.email 'Your E-mail linked to GitHub'`

2. (optional) Sometimes, using a GUI can be convenient for interacting with Git. GitHub Desktop has gotten pretty decent recently. The GitHub Desktop installation wizard also helps you with configuring Git such that you can skip step 1.



I have already uploaded videos for downloading packages and relevant information for those who have difficulty in understanding above mentioned points. 

[Installing R and RStudio](https://youtu.be/ZNBZevfYgo00),

[R Packages, Library, Errors](https://youtu.be/SRSNdCZ_QnE),

[R Codes Basics](https://youtu.be/0IEfQdjc5mM)

